In [4]:
import torch

In [19]:
x=torch.arange(12,dtype=torch.float32)
x.shape
x=x.reshape(3,4)
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [15]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [28]:
y=torch.tensor([[1.0,2,4,7],
               [1,2,3,4],
               [3,4,6,7]]
               )
print(x,y)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]) tensor([[1., 2., 4., 7.],
        [1., 2., 3., 4.],
        [3., 4., 6., 7.]])


In [30]:
#按行合并
torch.cat((x,y),dim=0)
#按列合并
#torch.cat((x,y),dim=1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 1.,  2.,  4.,  7.],
        [ 1.,  2.,  3.,  4.],
        [ 3.,  4.,  6.,  7.]])

In [32]:
x.sum()

tensor(66.)

In [39]:
#广播机制,向量才会这样
x1=torch.arange(3).reshape(3,1)
y1=torch.arange(2).reshape(1,2)
x1+y1

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [44]:
z=torch.zeros_like(y)
z

tensor([[0, 0]])

In [51]:
import os
os.makedirs(os.path.join('..','data'),exist_ok=True)

data_file=os.path.join('..','data','house_tiny.csv')

with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,106000\n')
    f.write('NA,NA,106000\n')

In [54]:
import pandas as pd

data=pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  pave  127500
1       2.0   NaN  106000
2       4.0   NaN  106000
3       NaN   NaN  106000

In [59]:
inputs,outputs=data.iloc[:,0:2],data.iloc[:,2]
inputs=inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


C:\Users\29336\AppData\Local\Temp\ipykernel_28160\2223495382.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs=inputs.fillna(inputs.mean())


In [65]:
inputs=pd.get_dummies(inputs,dummy_na=True)
inputs

NumRooms  Alley_pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [68]:
X,y=torch.tensor(inputs.values),torch.tensor(outputs.values,dtype=torch.float32)
X,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 106000., 106000.]))